export default {
  id: "bynara",
  priority: 25,
  hasFree: true,
  alias: "bynara",
  uiAlias: "bynara",
  display: {
    name: "Bynara",
    icon: "neurology",
    color: "#2E81FE",
    textIcon: "BN",
    website: "https://router.bynara.id",
    notice: {
      text: "Bynara Router Free Tier — High performance multi-model gateway with generous free models.",
      apiKeyUrl: "https://router.bynara.id",
    },
  },
  category: "freeTier",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://router.bynara.id/v1/chat/completions",
    validateUrl: "https://router.bynara.id/v1/models",
    headers: {
      "HTTP-Referer": "https://9router.local",
      "X-Title": "9Router",
    },
  },
  models: [
    { id: "combo/free", name: "Bynara Free Combo", reasoning: true, vision: true },
    { id: "space-bunny-alpha-bynara", name: "Space Bunny Alpha byNara", reasoning: true, vision: true },
    { id: "agnes-2.5-flash", name: "Agnes 2.5 Flash", reasoning: true, vision: true },
    { id: "agnes-3-flash", name: "Agnes 3 Flash", reasoning: true, vision: true },
    { id: "agnes-video-v2.0", name: "Agnes Video 2.0" },
    { id: "claude-fable-5", name: "Claude Fable 5", vision: true },
    { id: "claude-fable-5.1", name: "Claude Fable 5.1", vision: true },
    { id: "claude-opus-4.8", name: "Claude Opus 4.8", vision: true },
    { id: "claude-opus-5", name: "Claude Opus 5", vision: true },
    { id: "claude-opus-5.5", name: "Claude Opus 5.5", vision: true },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5", vision: true },
    { id: "deepseek-v4-flash-alibaba", name: "Deepseek v4 Flash 0731 Alibaba", vision: true },
    { id: "deepseek-v4-flash-vision-exp", name: "DeepSeek V4 Flash Vision (exp)", vision: true },
    { id: "deepseek-v4-pro-alibaba", name: "Deepseek v4 Pro 0813 Alibaba" },
    { id: "deepseek-v4.1-flash", name: "Deepseek v4.1 Flash", reasoning: true, vision: true },
    { id: "gemini-3.1-pro-high", name: "Gemini 3.1 Pro High", vision: true },
    { id: "gemini-3.8-flash-high", name: "Gemini 3.8 Flash High", vision: true },
    { id: "glm-5.2", name: "GLM 5.2", reasoning: true },
    { id: "glm-5.3", name: "GLM 5.3", reasoning: true },
    { id: "glm-5.3-flash", name: "GLM 5.3 Flash", reasoning: true, vision: true },
    { id: "gpt-5.6-luna", name: "GPT 5.6 Luna", vision: true },
    { id: "gpt-5.6-sol", name: "GPT 5.6 Sol", vision: true },
    { id: "gpt-5.6-terra", name: "GPT 5.6 Terra", reasoning: true, vision: true },
    { id: "gpt-6-astra", name: "GPT 6 Astra", vision: true },
    { id: "gpt-6-luna", name: "GPT 6 Luna", vision: true },
    { id: "gpt-6-sol", name: "GPT 6 SOL", vision: true },
    { id: "jev", name: "Jev" },
    { id: "kimi-k2.7-code", name: "Kimi K2.7-code", reasoning: true, vision: true },
    { id: "kimi-k2.8-preview", name: "Kimi k2.8 Preview", vision: true },
    { id: "kimi-k3", name: "Kimi K3", vision: true },
    { id: "laguna-s-2.1", name: "Laguna S 2.1", reasoning: true },
    { id: "ling-3.0-flash-fin-free", name: "Ling 3.0 Flash Fin Free", reasoning: true },
    { id: "ling-3.0-flash-sante-free", name: "Ling 3.0 Flash Sante Free", reasoning: true },
    { id: "longcat-2.5", name: "LongCat 2.5", reasoning: true },
    { id: "mimo-v2.5", name: "MiMo v2.5", vision: true },
    { id: "mimo-v2.5-free", name: "Mimo v2.5 Free", vision: true },
    { id: "mimo-v2.6-flash", name: "MiMo V2.6 Flash", vision: true },
    { id: "mimo-v2.6-flash-free", name: "Mimo v2.6 Flash Free", vision: true },
    { id: "mimo-v2.6-pro", name: "MiMo V2.6 Pro", reasoning: true, vision: true },
    { id: "minimax-m3", name: "MiniMax M3", vision: true },
    { id: "muse-spark-1.2", name: "Muse Spark 1.2", vision: true },
    { id: "muse-spark-1.2-contributor", name: "Muse Spark 1.2 Contributor", vision: true },
    { id: "muse-spark-1.3", name: "Muse Spark 1.3", vision: true },
    { id: "muse-spark-1.3-contributor", name: "Muse Spark 1.3 Contributor", vision: true },
    { id: "muse-spark-1.3-contributor-free", name: "Muse Spark 1.3 Contributor Free", vision: true },
    { id: "nemotron-3-super-free", name: "Nemotron 3 Super Free", reasoning: true },
    { id: "nemotron-3-ultra-free", name: "Nemotron 3 Ultra Free", reasoning: true },
    { id: "nemotron-3.5-lightning-free", name: "Nemotron 3.5 Lightning", reasoning: true },
    { id: "qwen3.8-27b", name: "Qwen 3.8 27B" },
    { id: "qwen3.8-flash", name: "Qwen 3.8 Flash", reasoning: true, vision: true },
    { id: "qwen3.8-max", name: "Qwen3.8-Max", vision: true },
    { id: "qwen3.8-max-alibaba", name: "Qwen3.8-Max Alibaba", vision: true },
    { id: "space-bunny-alpha", name: "Space Bunny Alpha", reasoning: true, vision: true },
    { id: "step-5-preview", name: "Step 5 Preview", reasoning: true, vision: true },
    { id: "stepfun-3.7-flash", name: "Stepfun 3.7 Flash", reasoning: true, vision: true },
    { id: "deepseek-v4-flash", name: "DeepSeek v4 Flash 0731" },
    { id: "deepseek-v4-pro", name: "DeepSeek v4 Pro 0813", reasoning: true },
    { id: "mimo-v2.5-pro", name: "MiMo v2.5 Pro" }
  ],
  serviceKinds: ["llm", "imageToText"],
  modelsFetcher: { url: "https://router.bynara.id/v1/models", type: "openai" },
  passthroughModels: true,
};
