export default {
  id: "geraikita",
  priority: 26,
  hasFree: true,
  alias: "geraikita",
  uiAlias: "geraikita",
  display: {
    name: "GeraiKita",
    icon: "neurology",
    color: "#7239C9",
    textIcon: "GK",
    website: "https://ai.geraikita.com",
    notice: {
      text: "GeraiKita Claude Bansos Free Tier — OpenAI-compatible gateway with 1M context models.",
      apiKeyUrl: "https://ai.geraikita.com",
    },
  },
  category: "freeTier",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://ai.geraikita.com/v1/claude/chat/completions",
    validateUrl: "https://ai.geraikita.com/v1/claude/models",
    headers: {
      "HTTP-Referer": "https://9router.local",
      "X-Title": "9Router",
    },
  },
  models: [
    { id: "claude-haiku-4.5", name: "Claude Haiku 4.5", reasoning: true, vision: true },
    { id: "gpt-5.6-sol", name: "GPT 5.6 Sol (1M)", reasoning: true, vision: true },
    { id: "gpt-5.6-terra", name: "GPT 5.6 Terra (1M)", reasoning: true, vision: true },
    { id: "gpt-5.6-luna", name: "GPT 5.6 Luna (1M)", reasoning: true, vision: true },
    { id: "glm-4.7-flash", name: "GLM 4.7 Flash", reasoning: true, vision: true },
    { id: "glm-5", name: "GLM 5 Frontier", reasoning: true },
    { id: "glm-4.7", name: "GLM 4.7 Versatile", reasoning: true },
    { id: "kimi-k2.5", name: "Kimi K2.5 Agentic", reasoning: true, vision: true },
    { id: "minimax-m2.5", name: "MiniMax M2.5 Reasoning", reasoning: true },
    { id: "minimax-m2.1", name: "MiniMax M2.1", reasoning: true },
    { id: "deepseek-v3.2", name: "DeepSeek V3.2", reasoning: true },
    { id: "gk/claude-haiku-4.5", name: "GK Claude Haiku 4.5" },
    { id: "gk/gpt-5.6-sol", name: "GK GPT 5.6 Sol" },
    { id: "gk/gpt-5.6-terra", name: "GK GPT 5.6 Terra" },
    { id: "gk/gpt-5.6-luna", name: "GK GPT 5.6 Luna" },
    { id: "gk/deepseek-v3.2", name: "GK DeepSeek V3.2" }
  ],
  serviceKinds: ["llm"],
  modelsFetcher: { url: "https://ai.geraikita.com/v1/claude/models", type: "openai" },
  passthroughModels: true,
};
